# Generated by Django 3.2.9 on 2022-04-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_it_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_name', models.CharField(max_length=150)),
                ('tutorial_description', models.TextField(max_length=200)),
                ('tutorial_photo', models.ImageField(upload_to='tutorial-photos')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.mainuser')),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'More Tutorials',
            },
        ),
        migrations.CreateModel(
            name='TutorialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_videos', models.FileField(upload_to='tutorial-videos')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tutorial')),
            ],
            options={
                'verbose_name': "Tutorial's media file",
                'verbose_name_plural': 'Tutorials media file',
            },
        ),
    ]
