# Generated by Django 3.2.9 on 2022-04-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
