# Generated by Django 3.2.9 on 2022-04-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220421_1054'),
        ('base', '0002_tutorial_tutorial_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tutorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.mainuser')),
            ],
            options={
                'verbose_name': 'Enrolled Tutorial',
                'verbose_name_plural': 'Enrolled Tutorials',
            },
        ),
    ]
