# Generated by Django 3.2.9 on 2022-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220513_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialmedia',
            name='tutorial_videos',
            field=models.URLField(verbose_name='YouTube URL: '),
        ),
    ]
