# Generated by Django 3.2.9 on 2022-05-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_tutorialmedia_tutorial_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialmedia',
            name='tutorial_videos',
            field=models.FileField(upload_to='tutorial-videos'),
        ),
    ]
