# Generated by Django 3.2.9 on 2022-06-14 13:26

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_tutorialmedia_tutorial_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialmedia',
            name='tutorial_videos',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
