# Generated by Django 3.2.9 on 2022-04-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='it',
            options={'verbose_name': "Yo'nalish", 'verbose_name_plural': "Yo'nalishlar"},
        ),
    ]
