# Generated by Django 3.2.9 on 2022-04-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_it_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='users-avatar'),
            preserve_default=False,
        ),
    ]
