# Generated by Django 3.2.9 on 2022-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_mainuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='login_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
